### ISSUE TITLE
Customization of PlantUML jar path (& Java binary?)

### ISSUE THREAD

**Issue by dracorpg** [jbn/IPlantUML#7]
First, thanks for the good work! If find this extension to be a simple yet very useful example of the potential behind Jupyter :)

The current mechanism allowing path customization for the PlantUML .jar file uses an option passed to setup.py at install time. This precludes `pip install iplantuml` and seems unnecessarily unwieldy to me.

Why not use an age-old but customization-friendly environment variable for this purpose insead? Something like `PLANTUML_JAR_FILE` would do the trick.

Or maybe the java executable could even be part of the variable (like https://pypi.python.org/pypi/sphinxcontrib-plantuml does it) so it would be more `PLANTUML_RUN_COMMAND`.

The second option would be extra convenient in situations where the Java binary is not on the PATH. For example my Windows dev box has no JRE installed, but a version of it is bundled with PyCharm: I'd rather not have its java.exe on the PATH but wouldn't mind using it for the specific purpose of running PlantUML, just as the [plantuml4idea](https://github.com/esteinberg/plantuml4idea) plugin runs it inside PyCharm (I am fully aware, however, that this is a matter of convenience and consider the ability to customize this of lesser importance than customizing the .jar path).

**Comment by jbn** [comment]
Hey there. 

Sorry, I think I conflated your issue and @bitaxis's PR from a few weeks back in my head. (Been a really busy few weeks.) I accepted his PR and will be pushing out a new version in a bit. His defaults were more sensible. 

See: https://github.com/jbn/IPlantUML/pull/6
